SELECT TOP (100) [customer_id]
      ,[first_name]
      ,[last_name]
      ,[email]
      ,[age]
      ,[gender]
      ,[city]
      ,[state]
      ,[country]
      ,[product_category]
      ,[product_preference]
  FROM [EShop].[dbo].[Product Preferences eshop]
